### ISSUE TITLE
NameError: name 'rgs' is not defined

### ISSUE THREAD

**Issue by yoursunny** [UCLA-IRL/ndn-hydra#21]
## Environment

* Linux kernel 5.4.0
* Docker `python:3.9` image
* NFD `0.7.1-30-ga103334b`, Unix socket mounted into the container at `/run/nfd.sock`
* NFD uses multicast strategy for all prefixes
* ndn-hydra 0.2.1 installed via pip

## Steps to reproduce

```shell
root@4c4540439250:/# ndn-hydra-repo -rp /hydra -n $(hostname -s) -s $RANDOM
Traceback (most recent call last):
  File "/usr/local/bin/ndn-hydra-repo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/ndn_hydra/repo/main/main.py", line 154, in main
    cmd_args = process_cmd_opts()
  File "/usr/local/lib/python3.9/site-packages/ndn_hydra/repo/main/main.py", line 80, in process_cmd_opts
    args = parse_cmd_opts()
  File "/usr/local/lib/python3.9/site-packages/ndn_hydra/repo/main/main.py", line 73, in parse_cmd_opts
    rgs["logging_path"] = "{workpath}/session.log".format(workpath=workpath)
NameError: name 'rgs' is not defined
```

**Comment by justincpresley** [comment]
Minor Typo that caused this error and the other one. 

Silly me...
