### ISSUE TITLE
 ndn-hydra fails to start if ~/.ndn directory is deleted

### ISSUE THREAD

**Issue by yoursunny** [UCLA-IRL/ndn-hydra#22]
## Environment

* Linux kernel 5.4.0
* Docker `python:3.9` image
* NFD `0.7.1-30-ga103334b`, Unix socket mounted into the container at `/run/nfd.sock`
* NFD uses multicast strategy for all prefixes
* ndn-hydra 0.2.1 installed via pip
* applied workaround for #21:
  `sed -i 's/\brgs\b/args/' /usr/local/lib/python3.9/site-packages/ndn_hydra/repo/main/main.py`

## Steps to reproduce

```shell
root@4c4540439250:/# rm -rf ~/.ndn
root@4c4540439250:/# ndn-hydra-repo -rp /hydra -n $(hostname -s) -s $RANDOM
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/ndn_hydra/repo/main/main.py", line 117, in run
    app = NDNApp()
  File "/usr/local/lib/python3.9/site-packages/ndn/app.py", line 63, in __init__
    self.keychain = default_keychain(config['pib'], config['tpm'])
  File "/usr/local/lib/python3.9/site-packages/ndn/client_conf.py", line 101, in default_keychain
    pib = KeychainSqlite3(os.path.join(pib_loc, 'pib.db'), tpm)
  File "/usr/local/lib/python3.9/site-packages/ndn/security/keychain/keychain_sqlite3.py", line 277, in __init__
    cursor = self.conn.execute('SELECT tpm_locator FROM tpmInfo')
sqlite3.OperationalError: no such table: tpmInfo
```

It's same error as #14, which is not resolved.

**Comment by justincpresley** [comment]
See if 0.2.2 doesn't solve this issue.

**Comment by yoursunny** [comment]
This issue persists in ndn-hydra 0.2.2.

**Comment by yoursunny** [comment]
I see the following in documentation:

> A NDN Hydra node will require a identity (along with a key) that is the same as the node_name. For now however, the default localhost/default key that NFD produces automatically is required in order to have a successful run. Deleting ~/.ndn or the default keys will result in the inability to run a hydra node.

It's still misleading:

* If NFD was installed via systemd or in a Docker container, its keychain is in a different location, and it would not "produce automatically" a key in `~/.ndn`.
* If YaNFD or some other forwarder is used, it would not have the keychain either.

Thus, ndn-hydra guide should explicitly specify what keys should be created, instead of relying on some other program might "produce automatically" a key.

**Comment by justincpresley** [comment]
Yes,, you can resolve this issue by creating a certificate with an identity. Use ```ndnsec key-gen``` followed by a NAME.

**Comment by susmit85** [comment]
Justin, was there any resolution to this? We are still seeing this problem.
